version: '3.8'

services:
  steppers-life-pwa:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Optional: Mount SSL certificates
      # - ./ssl:/etc/nginx/ssl:ro
      # Optional: Custom nginx config
      # - ./nginx-pwa.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=your-domain.com
    restart: unless-stopped
    networks:
      - pwa-network

networks:
  pwa-network:
    driver: bridge 