// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getEnv } from '@/lib/env';

const SUPABASE_URL = getEnv('VITE_SUPABASE_URL', "https://intcywjfnyjvvsypsetr.supabase.co");
const SUPABASE_PUBLISHABLE_KEY = getEnv('VITE_SUPABASE_ANON_KEY', "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludGN5d2pmbnlqdnZzeXBzZXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjY3MTIsImV4cCI6MjA2NTE0MjcxMn0.DI67uUEpAKFwDgTpBxWZXu2mINdOtTEO1PhjK8fYPPI");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);