// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getEnv } from '@/lib/env';

const SUPABASE_URL = getEnv('VITE_SUPABASE_URL', "https://revmdncwzztxxinjlzoc.supabase.co");
const SUPABASE_PUBLISHABLE_KEY = getEnv('VITE_SUPABASE_ANON_KEY', "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJldm1kbmN3enp0eHhpbmpsem9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzY4NjEsImV4cCI6MjA2NDQ1Mjg2MX0.J7Wj8t8gYsErt29TsFXyPGAR7YbUEKdlbCeUTJwK7ic");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);